---
Name: gisconfig
---
SilverStripe\Core\Injector\Injector:
  TileRenderer:
    class: Smindel\GIS\Service\GDRenderer
SilverStripe\ORM\DataObject:
  tile_renderer: 'vector_renderer'
SilverStripe\Assets\File:
  tile_renderer: 'raster_renderer'
